DROP TABLE USER CASCADE;
DROP TABLE TEMA CASCADE;

CREATE TABLE USER (
    USERNAME varchar(255) PRIMARY KEY,
    PASS varchar(255) NOT NULL
);

CREATE TABLE TEMA(
    TNOMBRE varchar(255) PRIMARY KEY,
    DESCRIPCION varchar(500)
);

CREATE TABLE POST(
    ID_POST INT AUTO_INCREMENT PRIMARY KEY,
    TNOMBRE varchar(255) NOT NULL,
    TITULO varchar(255) NOT NULL,
    USERNAME varchar (255) NOT NULL,
    CONTENIDO varchar(255) NOT NULL,
    CONSTRAINT FK_TNOMBRE FOREIGN KEY (TNOMBRE) REFERENCES TEMA(TNOMBRE),
    CONSTRAINT FK_USERNAME FOREIGN KEY (USERNAME) REFERENCES USER(USERNAME)
);

CREATE TABLE COMMENT(
    ID_COMMENT INT AUTO_INCREMENT PRIMARY KEY,
    
);