# Generated by Django 4.1.5 on 2023-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='foto',
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto1',
            field=models.ImageField(null=True, upload_to='noti'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto2',
            field=models.ImageField(null=True, upload_to='noti'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto3',
            field=models.ImageField(null=True, upload_to='noti'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto4',
            field=models.ImageField(null=True, upload_to='noti'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='foto5',
            field=models.ImageField(null=True, upload_to='noti'),
        ),
    ]
